### ISSUE TITLE
Is error email supposed to also be success email?

### ISSUE THREAD

**Issue by 123andy** [IUREDCap/redcap-etl-module#10]
(Loving the module - great work)
I configured the 'error email' settings for our ETL only expecting 'errors' to result in emails but it seems to email on success as well.  Is this intended?  Should there be an option for only email on errors?

**Comment by mullen2** [comment]
@123andy Thanks Andy.

If you only want e-mail to be sent when there is an error, then the "E-mail errors" option should be checked, and the "E-mail summary" option should be _unchecked_. If that is how you have things set, and you are receiving e-mails even when there are no errors, then that would be a bug.

**Comment by 123andy** [comment]
Thanks - all too obvious for someone like me.
