### ISSUE TITLE
Data entered on survey disappearing when using @IMAGEMAP action tag (REDCap 9.4.1, Imagemap v1.4.4)

### ISSUE THREAD

**Issue by jcjohnsonmo** [IUREDCap/redcap-etl-module#11]
The issue here is that I had data entered into a survey that was disappearing when I went to the next page. At Rob Taylor's suggestion, I determined that this issue is resolved when the @IMAGEMAP action tag is removed. The screenshots are provided below and the demonstration xml file is available on the REDCap Community page: https://community.projectredcap.org/questions/78059/data-entered-on-survey-disappearing-due-to-section.html .

Project Design: I have 2 instruments, Pre and Post. In both instruments, I have an imagemap (@IMAGEMAP=DO_TOUCH_NET_BODY_GREY) and fields for each body region where the severity of the pain is assessed, if the body region is selected on the imagemap. Additionally on the Post instrument, there is a matrix field where the rows show up if the severity on the Post instrument is worse than the severity on the Pre instrument.

Issue: When more than one body region has worse severity, only the first one in the list shows up in the matrix field. Additionally if you return to the previous page on the Post instrument, the severities for the other body regions have disappeared. This behavior only happens in Survey Mode, not Data Entry Mode.

Notes: After many hours of testing, @frgeof and I found how to prevent this from happening. Method 1: Change the survey setting Question Display Format to "All on one page". Method 2: Change the matrix field to separate fields and remove the Section Break. Additionally at Rob Taylor's suggestion, we found that removing the @IMAGEMAP action tag on the Post instrument solves the issue.

![S1](https://user-images.githubusercontent.com/25780881/74165850-51ccde80-4beb-11ea-81e7-9f506ab48c02.png)
![S2](https://user-images.githubusercontent.com/25780881/74165851-52657500-4beb-11ea-8d4d-730378961a52.png)
![S4](https://user-images.githubusercontent.com/25780881/74165852-52657500-4beb-11ea-9861-4a2d1766b2ba.png)
![S5](https://user-images.githubusercontent.com/25780881/74165854-52657500-4beb-11ea-858e-a060adb1a277.png)
![S6](https://user-images.githubusercontent.com/25780881/74165855-52fe0b80-4beb-11ea-9b01-92a019330cca.png)
![S7](https://user-images.githubusercontent.com/25780881/74165857-52fe0b80-4beb-11ea-942b-1035407e943f.png)

**Comment by aarenson** [comment]
Jane, how does this relate to the REDCap-ETL external module? Did you mean to post this on the REDCap Community site, perhaps?

**Comment by mullen2** [comment]
@jcjohnsonmo, I think this is the GitHub repo for the image map external module: https://github.com/marlycormar/imagemap

**Comment by jcjohnsonmo** [comment]
My sincere apologies. Please color me shame-faced for posting this in the wrong repo. Thanks for directing me to the correct repo.
