### ISSUE TITLE
Allow the fields of type 'file' to be included in export

### ISSUE THREAD

**Issue by targetpharma** [IUREDCap/redcap-etl-module#13]
If I try to manually include a field of type 'file' in the configuration:
> FIELD,nxfile,file

I get an error during export:
> Invalid field type "file" on line 19: "FIELD,nxfile,file"

If I change the type from 'file' to 'string:
> FIELD,nxfile,string

Then the the field does not appear in the export.

Currently in `RulesGenerator.php`, fields of type 'file' are ignored and not included.

```php
    protected function getFieldRule($field)
    {
...
        if ($fieldType === 'descriptive' || $fieldType === 'file') {
            ; // Don't do anything
        }
...
```

This issue is for a request to be able to include fields of type 'file' in an export.

Now, obviously, the file contents cannot be included, so that leaves two options:

1. Include flag field that indicates if a file is present.
2. Include file name field that can be used to see if a file is present and also stores the name of the file as it was uploaded to the form.

**Comment by mullen2** [comment]
@targetpharma Thanks for your further feedback.

I looked into this, and option 1 seems like it might be fairly easy to implement. REDCap-ETL is built on top of the REDCap API, and for exporting records, it appears to return "[document]" if a file has been uploaded, or "" if not.

I think it would be possible to download the file contents into the database (I'll refer to that as option 3). For option 2, the only way I can see to get the file name (using the REDCap API), is to actually download the file and look at the header of the response. So for both option 2 and 3, the module would need to make a separate API call for each file in the REDCap project that downloads the file. I imagine that the performance of this could be really bad.

Would option 1 be helpful for you?

Jim

**Comment by targetpharma** [comment]
Thanks for the quick response.

> Would option 1 be helpful for you?

Yes, in this case it would be helpful.

I recall looking at something similar a while back and also being unimpressed with the APIs ability to provide metadata about files attached to forms, so it doesn't surprise me that downloading the file is the only option to get at the file name.

**Comment by mullen2** [comment]
I looked into this further, and it doesn't look like it will be as easy as I first thought. The underlying REDCap API method being used to return the fields to export doesn't include file fields. I also have some other work on REDCap-ETL right now that is very high priority that I need to complete.

I have added this to the agenda for our group meeting for next week. I'll see what others think.

**Comment by targetpharma** [comment]
Thanks for the update!

**Comment by mullen2** [comment]
A flag that indicates if a file field contains a document was added in release 1.2.1. And an option was added for including file fields when transformation rules are auto-generated.
