### ISSUE TITLE
XSS vulnerabilty

### ISSUE THREAD

**Issue by utiso** [IUREDCap/redcap-etl-module#28]
During a routine check of our system, we discovered a Cross-Site Scripting vulnerability in the redcap-etl module. 

Vulnerable end-point:
_/ExternalModules/?prefix=redcap_etl_module&page=web%2Fadmin%2Fhelp_edit_

Vulnerable parameter:
`customHelp`

parameter value:
`<h1 onmouseover=alert("xss")>test</h1>`

The above parameter value allowed us to insert our own JavaScript into web page rendered by the module. While popping up an alert box is harmless, an attacker could leverage this vulnerability to inject code that makes requests on behalf of users or exfiltrates data from the site.

**Comment by aarenson** [comment]
Thank you for reporting this!

**Comment by mullen2** [comment]
@utiso Thanks again for letting us know. I have fixed this vulnerability in the code, and I have started the process for making the release for this change.

**Comment by mullen2** [comment]
@utiso This issue has been fixed in release 1.4.1.
