### ISSUE TITLE
PHP Fatal Error when viewing the user manual

### ISSUE THREAD

**Issue by tranpl** [IUREDCap/redcap-etl-module#41]
Getting a fatal error when trying to view the user manual. I checked the source just in case and don't see a 'faise' constant.
Version 2.4.4 with REDCap 14.6.1
![image](https://github.com/user-attachments/assets/9d2599d3-1d29-4424-8c56-86a7f191a99c)

**Comment by mullen2** [comment]
@tranpl Thanks for finding this. I have fixed this in the code and improved the automated tests to check for this and simliar problems going forward. I have submitted the new version (2.4.5) to the external module repository, and hopefully it will be added soon.

**Comment by mullen2** [comment]
@tranpl The new version has been added to the external module repository.
