### ISSUE TITLE
web/run.php puts the HTML for refreshing its page into the CVS zip file

### ISSUE THREAD

**Issue by aarenson** [IUREDCap/redcap-etl-module#44]
After upgrading httpd from 2.4.57 to 2.4.62, web/run.php now appends the HTML response that would normally be rendered by the browser into the CVS file, if one is created.

From what I've, briefly, read, it's not generally expected that a single PHP executable would be able to return more than one set of content. One way to work around this is move the code that generates the Content-Type: application/zip into a second file, and then include a redirect at the end of the HTML to the new, second file. This way the html would be rendered and then the redirect would cause the zip file to be downloaded.

We are holding the update of httpd on our production server until this issue is resolved.

**Comment by aarenson** [comment]
I suppose it wouldn't strictly HAVE to be in a separate file, but the web/run.php could have logic to either create the CSV file <OR> generate its own page.

**Comment by aarenson** [comment]
I think I've found a one line fix. Add exit(0); after writing out the CSV file and it seems to work.

**Comment by mullen2** [comment]
@aarenson Andy, thanks for finding this and the information on the fix. This should be fixed in version 2.4.7.
