### ISSUE TITLE
EM Cron cant send an exception email 

### ISSUE THREAD

**Issue by ihabzee** [IUREDCap/redcap-etl-module#45]
Hi There, 
ETL cron is throwing an exception and the EM can't send the email to admins. 

```
Cron job 'redcap_etl' failed for External Module 'redcap_etl_module'.

Exception: Error: Call to a member function getMessage() on string in /var/www/html/modules/redcap_etl_module_v2.4.7/vendor/iu-redcap/redcap-etl/src/Logger.php:311
Stack trace:
#0 /var/www/html/modules/redcap_etl_module_v2.4.7/vendor/iu-redcap/redcap-etl/src/Logger.php(570): IU\REDCapETL\Logger->logLoggingError()
#1 /var/www/html/modules/redcap_etl_module_v2.4.7/vendor/iu-redcap/redcap-etl/src/Logger.php(391): IU\REDCapETL\Logger->logEmailSummary()
#2 /var/www/html/modules/redcap_etl_module_v2.4.7/classes/ServerConfig.php(475): IU\REDCapETL\Logger->logException()
#3 /var/www/html/modules/redcap_etl_module_v2.4.7/RedCapEtlModule.php(309): IU\RedCapEtlModule\ServerConfig->run()
#4 /var/www/html/modules/redcap_etl_module_v2.4.7/RedCapEtlModule.php(1939): IU\RedCapEtlModule\RedCapEtlModule->run()
#5 /var/www/html/modules/redcap_etl_module_v2.4.7/RedCapEtlModule.php(154): IU\RedCapEtlModule\RedCapEtlModule->runTaskCronJobs()
#6 /var/www/html/modules/redcap_etl_module_v2.4.7/RedCapEtlModule.php(138): IU\RedCapEtlModule\RedCapEtlModule->runCronJobs()
#7 /var/www/html/redcap_v14.7.5/ExternalModules/classes/ExternalModules.php(6471): IU\RedCapEtlModule\RedCapEtlModule->cron()
#8 /var/www/html/redcap_v14.7.5/Classes/Cron.php(334): ExternalModules\ExternalModules::callCronMethod()
#9 /var/www/html/redcap_v14.7.5/cron.php(23): Cron->execute()
#10 /var/www/html/cron.php(9): include('...')
#11 {main}
```

**Comment by mullen2** [comment]
@ihabzee From the above error message, it appears that you are using version 2.4.7 or the REDCap-ETL external module. Did this problem just start with this version? Version 2.4.7 was just released today, but I can't think of any change offhand that would cause such an error.

**Comment by ihabzee** [comment]
No, this issue started with 2.4.5. I upgraded to the latest version to see if it would be fixed, but the issue persists.

**Comment by mullen2** [comment]
@ihabzee Thanks for reporting this. I looked at the code, and this definitley appears to be a bug. I am working on a fix.

**Comment by mullen2** [comment]
@ihabzee The errors you have found are related to error handling for the case where e-mail logging is faling for one or more of the e-mail addresses specified. It is possible that you have an incorrect e-mail address specified for e-mail logging. So, _if_ that is the case, you might be able to get rid of this error by correcting or removing the incorrect e-mail address(es).

**Comment by ihabzee** [comment]
Thanks, @mullen2 for looking into this. I looked at configured emails and all of them seem to be correct and active.

**Comment by mullen2** [comment]
@ihabzee Version 2.4.8 was just released, which should fix the issue here. However, the code that was fixed is being called because e-mail sending for one or more of the specified e-mail addresses is failing, so I expect there will at least one other issue to figure out. REDCap-ETL needs the PHP mail function to be supported, so if your system does not support it, that would cause the e-mails to fail.

**Comment by ihabzee** [comment]
Thanks, @mullen2. Our REDCap instance uses the Mailgun API to send emails. PHP mail is not installed or configured in our instance. Would it be possible to send the email via the REDCap core send email method in the' Message` class?

**Comment by mullen2** [comment]
@ihabzee Unfortunately, no. REDCap-ETL was initially developed (and is still supported) as a stand alone application (https://github.com/IUREDCap/redcap-etl), and the REDCap-ETL external module uses the REDCap-ETL application as a library to do the actual ETL processing. The REDCap-ETL application sends the e-mail, and it has no link code-wise to REDCap. The REDCap-ETL application can be used by the REDCap-ETL external module as a remote ETL server, so it might not even be running on the REDCap server.

**Comment by ihabzee** [comment]
Got it, does the App log these errors to a log file or php_error.log?

**Comment by mullen2** [comment]
@ihabzee 

The error will be in the log that is accessible from the **REDCap-ETL admin interface** in the Control Center in REDCap:

![image](https://github.com/user-attachments/assets/55ee1e7b-3276-40fc-88d8-372aaaf57bf9)

**Server File Logging.** If you specify a log file in the ETL server configuration in the REDCap-ETL admin interface in the Control Center in REDCap, then the error should be logged to that file on the server also.

If **database logging** is enabled in the REDCap-ETL configuration for the project, then the error will be logged to the ETL target database in table etl_event_log, for example:

```
+--------------+--------+----------------------------+--------------------------------------------------------------------------------+
| log_event_id | log_id | time                       | message                                                                        |
+--------------+--------+----------------------------+--------------------------------------------------------------------------------+
|        23313 |    914 | 2024-12-06 09:23:08.531000 | Logging to e-mail failed for the following e-mail addreses: user@someplace.edu |
+--------------+--------+----------------------------+--------------------------------------------------------------------------------+
```

**Comment by ihabzee** [comment]
Perfect! Thank you so much for your help. I found the error log.
