### ISSUE TITLE
Document database SSL setting

### ISSUE THREAD

**Issue by mullen2** [IUREDCap/redcap-etl-module#5]
Need to document the database SSL setting. Users have gotten a database error, because database SSL is set, and, presumably, their database does not support SSL.

**Comment by 123andy** [comment]
We had the same thing happen to us and took us a while to find the setting.  I just made the following patch if you'd like to accept it to help reduce time people spend...
https://github.com/IUREDCap/redcap-etl-module/pull/9

**Comment by mullen2** [comment]
@123andy Yes, this sounds like a good idea. I didn't merge the pull request, because I need to make the change in the [REDCap-ETL](https://github.com/IUREDCap/redcap-etl/) repository, but plan to make this and other improvements.

**Comment by mullen2** [comment]
An enhanced error message for MySQL that mentions SSL as a possible cause (if SSL was specified). This change had been released in version 1.1.0.
