### ISSUE TITLE
Allow the survey identifier field and survey timestamp field(s) to be included in export

### ISSUE THREAD

**Issue by targetpharma** [IUREDCap/redcap-etl-module#7]
When creating a report via the REDCap, there is an option to `Include the survey identifier field and survey timestamp field(s)`

![image](https://user-images.githubusercontent.com/20141935/68951622-78b27a80-078c-11ea-93cd-9aaf00c632b3.png)

The survey timestamp fields are not stored in `redcap_data` but instead are stored in `redcap_surveys_response`.

However, the REDCap API for export records does have a `exportSurveyFields` parameter that will include the survey identifier fields in the export.

This issue is to request the feature of allowing of similar type of export from the ETL process.

The one sticky point I ran across was the near impossibility of determining which instruments are enabled as surveys using only the APIs. That would be necessary to include these survey identifier fields during the auto generation of the transformation rules.

**Comment by mullen2** [comment]
Exporting of the survey identifier field and the survey timestamp fields has been added to the REDCap-ETL application (https://github.com/IUREDCap/redcap-etl/releases/tag/1.1.0).

This capability will be added to the REDCap-ETL external module the next time its dependencies are updated and it is released.

**Comment by mullen2** [comment]
Fix released in version 1.1.0
